### ISSUE TITLE
Make coverage its own action?

### ISSUE THREAD

**Issue by christopher-dG** [julia-actions/julia-runtest#1]
IMO it would be nice to have separate actions for each logical stage of the build, rather than have the runtests action also submit coverage iff a token is available. 
This is mostly just a stylistic choice to make, really.

**Comment by SaschaMann** [comment]
I wrote down some thoughts on that in the other repo (wasn't sure where else to put it for now): https://github.com/julia-actions/setup-julia/issues/3

I think more atomic actions might be the way to go, too.

**Comment by davidanthoff** [comment]
I'm really split on this... On one hand I see the appeal, but on the other hand I think I would much prefer a simpler workflow config, where essentially as a pkg dev I automatically get new features for standard pkg workflow stuff without updating my config files...

**Comment by SaschaMann** [comment]
I can definitely see the appeal of setting up a workflow once, supplying the necessary secrets and then never having to touch it again. Otoh it's also quite appealing to have more control over workflows and potentially more complex CI setups without writing them from scratch.

I wonder if there will be all that many new features beyond the standard workflow that packages currently use (run tests, upload coverage results, potentially run benchmarks, deploy docs). In that case, once those actions are in place, one would likely not have to update config files after an initial setup.

We could create a sample workflow in advance, with placeholder options and actions, too. Then whenever a new feature is added, it would "just start working" because people already set it up in advance.

---

I linked this in the Actions thread on Discourse so that others can chime in. Don't think there really is a right or wrong answer here and more perspectives on it would be helpful.

**Comment by davidanthoff** [comment]
I thought more about it, and I'm on board with smaller actions that do one thing. Lets see how that goes, and then we can still revisit and add more aggregate stuff later if we want.

I'll split things up now.

**Comment by davidanthoff** [comment]
Ok, all done. I think I'll close this issue for now. Maybe we should actually just discuss broader design issues that span across actions in the discourse thread that @SaschaMann started a while ago?
