### ISSUE TITLE
Package Pkg not found in current path during testing

### ISSUE THREAD

**Issue by iliailmer** [julia-actions/julia-runtest#37]
We have a package that uses `julia-runtest` action during Github Actions CI. At test stage of CI we encounter this error:
```
ERROR: ArgumentError: Package Pkg not found in current path:
- Run `import Pkg; Pkg.add("Pkg")` to install the Pkg package.

Stacktrace:
 [1] require(::Module, ::Symbol) at ./loading.jl:893
ERROR: LoadError: failed process: Process(`/opt/hostedtoolcache/julia/1.5.3/x64/bin/julia -Cnative -J/opt/hostedtoolcache/julia/1.5.3/x64/lib/julia/sys.so --depwarn=yes --check-bounds=yes -O0 -g1 --code-coverage=user --color=yes --startup-file=no --startup-file=no --project=/home/runner/.julia/packages/GAP/Gc53G/gaproot/v1.5 -e 'using Pkg; Pkg.develop(PackageSpec(path="../..")); Pkg.resolve()'`, ProcessExited(1)) [1]
```

this is running on Ubuntu-latest with Julia-1.5.3, but the same occurred on macos-latest.
this does not occur locally and seems to be connected with `LOAD_PATH` environment variable. I submitted a similar issue to the package creators [here](https://github.com/oscar-system/GAP.jl/issues/635). I wonder if this can be fixed on the `runtest` side since locally it all works, so probably not a GAP issue.

**Comment by SaschaMann** [comment]
> this does not occur locally and seems to be connected with LOAD_PATH environment variable

The action doesn't touch the LOAD_PATH variable, and Pkg works in a fresh env (otherwise the previous steps and what leads up to the error wouldn't happen). So I'm not really sure if what causes this is related to the action.

Could you try replacing the step where julia-runtest is called with the test command to see if you can reproduce it? If it doesn't throw the same error in that case, there might be a bug in https://github.com/julia-actions/julia-runtest/blob/master/add_general_registry.jl

The command should be

```
julia --color=yes --check-bounds=yes --inline=yes --depwarn=yes --project=@. -e 'using Pkg; Pkg.test(coverage=true)'
```

**Comment by iliailmer** [comment]
@SaschaMann thank you for the suggestion, I did try it, and the error is still appearing.

**Comment by SaschaMann** [comment]
In that case I think it's not caused by the action but rather by some issue with the test suite of the package, perhaps one that only occurs in the GitHub Actions virtual environment? 🤷 

I read through https://github.com/oscar-system/GAP.jl/issues/635 and have no idea what could cause it though.
